/* empty css                      */import{a as b}from"./assets/vendor-CRwelqcB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const E="50595103-65097a90456797714ffdbb949",L="https://pixabay.com/api/",w=15;async function I(s,r){var i,t;const e=new URLSearchParams({key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:w});try{return(await b.get(`${L}?${e.toString()}`)).data}catch(o){throw console.error("Error fetching images from Pixabay:",o),new Error(((t=(i=o.response)==null?void 0:i.data)==null?void 0:t.message)||o.message||"Failed to fetch images")}}const c=document.getElementById("gallery"),d=document.querySelector(".loader"),m=document.getElementById("load-more-btn");let f;function P(s){if(!c){console.error("Gallery element not found!");return}const r=s.map(e=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <img
          class="gallery-image"
          src="${e.webformatURL}"
          alt="${e.tags}"
          loading="lazy"
        />
      </a>
      <div class="info">
        <p><b>Likes</b> ${e.likes}</p>
        <p><b>Views</b> ${e.views}</p>
        <p><b>Comments</b> ${e.comments}</p>
        <p><b>Downloads</b> ${e.downloads}</p>
      </div>
    </li>
  `).join("");c.insertAdjacentHTML("beforeend",r),f?f.refresh():f=new SimpleLightbox(".gallery a",{captionsData:"alt",captionDelay:250})}function R(){c&&(c.innerHTML="")}function v(){d&&d.classList.remove("is-hidden")}function g(){d&&d.classList.add("is-hidden")}function B(){m&&m.classList.remove("is-hidden")}function a(){m&&m.classList.add("is-hidden")}const h=document.getElementById("search-form"),T=document.getElementById("search-input"),$=document.getElementById("load-more-btn"),S=document.getElementById("gallery");let p="",l=1;const A=15,_=500;g();a();h.addEventListener("submit",async s=>{s.preventDefault();const r=T.value.trim();if(!r){iziToast.error({title:"Error",message:"Search query cannot be empty!",position:"topRight",timeout:3e3});return}p=r,l=1,R(),a(),await y(),h.reset()});$.addEventListener("click",async()=>{l++,await y(!0)});async function y(s=!1){v(),s&&a();const r=Date.now();try{const e=await I(p,l),i=Date.now()-r,t=_-i;if(t>0&&await new Promise(o=>setTimeout(o,t)),e.hits&&e.hits.length>0){if(P(e.hits),s){const n=S.lastElementChild;if(n){const u=n.getBoundingClientRect();u.height>0&&window.scrollBy({top:u.height*2,behavior:"smooth"})}}(l-1)*A+e.hits.length<e.totalHits?B():(a(),e.totalHits>0&&iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3}))}else a(),!s&&l===1?iziToast.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3}):e.totalHits>0&&iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3})}catch(e){console.error("Search or load more failed:",e),iziToast.error({title:"Error",message:`Failed to fetch images: ${e.message||"Unknown error"}. Please try again later.`,position:"topRight",timeout:5e3}),a()}finally{g()}}
//# sourceMappingURL=index.js.map
